---
title: "Contributors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contributors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = FALSE}
library(tdcm)

tdcm_desc_file <- system.file("DESCRIPTION", package = "tdcm")
tdcm_desc <- as.data.frame(read.dcf(tdcm_desc_file))
tdcm_maintainer <- tdcm_desc["Maintainer"]
tdcm_authors <- tdcm_desc["Authors@R"] |> parse(text = _) |> eval()

li_author <- function(author) {
  name <- paste(author$given, author$family)
  email <- author$email
  cat(paste("*", name, paste0("&lt;", email, "&gt;"), "\n"))
} # li_person
```

## Maintainer

* `r tdcm_maintainer`

<small>
The list above was generated from the package's `DESCRIPTION` file. See 
[CITATION](../authors.html) for additional information.
</small>

## Authors

```{r, echo=FALSE, results='asis'}
for (tdcm_author in tdcm_authors) {
  if ("aut" %in% tdcm_author$role) {
    li_author(tdcm_author)
  } # if
} # for
```

<small>
The list above was generated from the package's `DESCRIPTION` file. See 
[CITATION](../authors.html) for additional information.
</small>

## Additional Contributors

* TODO

